---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#
- name: set internal vars for 1.8.0_66
  set_fact:
    jdk_version:      1.8.0_66
    jdk_tarball_file: jdk-8u66-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-linux-x64
  when: java_version == 8 and java_subversion == 66
